// <auto-generated />
namespace CR160471_Desafio01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class idcliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(idcliente));
        
        string IMigrationMetadata.Id
        {
            get { return "202110022313070_idcliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
