// <auto-generated />
namespace CR160471_Desafio01.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class tipocuentabancaria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(tipocuentabancaria));
        
        string IMigrationMetadata.Id
        {
            get { return "202110022248119_tipocuentabancaria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
